# CrazedCraft network Components plugin - Settings.yml config file
settings:
    # Enable testing mode?
    testing-mode: false
    # Time until the server automatically restarts in seconds
    restart-time: 3600
    # Which command's should be sent to clients by default?
    command-data:
        - default
    # Whats the most amount of requests we should execute in one async task?
    request-batch-throttle: 10
    # Network sync information
    network:
        # Should we enable network sync?
        # The server will still submit data but it won't read any
        # ** Not implemented yet! **
        enable: true
        # Server type/node
        # ** Do not input any value here without checking with database and/or other staff first or the server won't sync properly **
        node: "Hub"
        # Server number/id
        # ** Do not input any value here without checking with database and/or other staff first or the server won't sync properly **
        id: 1
        # Time in ticks in which the server should sync with the database
        sync-interval: 100
    # Database credentials
    database:
        host: "172.106.17.114"
        username: "12"
        password: "0d5b45c4ee"
        schema: "12"
        port: 3306