# CrazedCraft network Components plugin - Settings.yml config file
settings:
  # Enable testing mode?
  testing-mode: false
  # Time until the server automatically restarts in seconds
  restart-time: 3600
  # Which command's should be sent to clients by default?
  command-data:
    - default
  # Database credentials
  database:
    host: "172.106.17.114"
    user: "12"
    password: "0d5b45c4ee"
    name: "12"
    port: 3306